#+title: blk06
#+date: <2025-11-04 Tue>


* Advanced Electricity

starter generator: when you employ a generator and a starter combined into one unit.

AC Alternators: Found on aircraft that use a large amount of electrical power.

CSD: Constant-Speed Drive
- to ensure the alternator rotates at the correct speed to ensure a 400-Hz frequency.

Two most common units:
- Bus Power Control Unit (BPCU)

- GCU (Generator Control Unit)

AC alternator control systems on large transport category aircraft have redundant systems.

An inverter is used to provide AC when needed for light aircraft.(Changes DC to AC)

** Wiring Diagrams

Two most generally used conductors are: *Copper and Aluminum*

The proper conduit size for a specific wire bundle or cable require that the conduit inner diameter should be ~25% larger than the anticipated maximum diameter of the wires.

Shielding is the process of applying a metalic covering to wiring and equipment to eliminate electromagnetic interference (EMI).

The AMM must be followed to replace a wire.

Wire is manufactured in sizes according to a standard known as the *American Wire Gauge (AWG)*

Aircraft electrical system wiring and cable may be marked with a combination of *letters, numbers and colors.*

Identification and markings should be placed at each end of the wire and at *15" maximum intervals* along the length of the wire.

Recommended *procedures for installing* aircraft wiring:
- /Open Wiring:/ Open wiring is any wire, wire group or wire bundle not enclose in a conduit.

- /Wire Group:/ A Wire group is two or more wires going to the same location and physically ties together to retain their group identity.
